### ISSUE TITLE
Web Dev Repo Project Setup

### ISSUE THREAD

**Issue by TheHappyBaloney** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#1]
Set up the foundational structure for the Web Dev repository:

1. Initialize Astro with TypeScript.
2. Integrate with @astrojs/react.
3. Configure ESLint (Airbnb) and Prettier.
4. Implement ESLint and Prettier checks on CI or via pre-commit hooks with Husky.
5. Set up font and Radix UI.
6. Link the project with Netlify for deployment.
7. Setup i18n - i18n: { defaultLocale: "en", locales : [ "en" , "bn" ], }

**Comment by wriddhi** [comment]
Hey this is nox

**Comment by AyanavaKarmakar** [comment]
Hi @TheHappyBaloney, this is rbbbtz.
