### ISSUE TITLE
feat: add OG tags

### ISSUE THREAD

**Issue by AyanavaKarmakar** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#103]
### Is your feature request related to a problem? Please describe.

maybe we can use this? https://astro.build/integrations?search=images

### Describe the solution you'd like to see

N/A

### Describe alternate solutions

N/A

**Comment by Ayushk249** [comment]
Could you explain what we need to do? I can try this out but I am new to open source contribution

**Comment by AyanavaKarmakar** [comment]
Hi @Ayushk249. We want to add OpenGraph Meta Tags to show images as embeds like this - 

![image](https://github.com/user-attachments/assets/ed65adef-a728-447d-9a8a-6775ae350c7e)

You can refer to this site to understand how Netlify does it: https://www.opengraph.xyz/url/https%3A%2F%2Fwww.netlify.com

1) The OG images must be different for the 2 layouts in `/src/layouts`.
2) The URLs for OG Images should be exported as constants from `/src/constants/socials.ts`.
3) We haven't decided on what images to use _yet_, so please use placeholder images URLs temporarily.

Feel free to [join our discord server](https://discord.com/invite/xxSXWYf6d4) so that we can clear your doubts quickly!

**Comment by yashchaurasia667** [comment]
can you assign it to me?
