### ISSUE TITLE
feat: add marker clustering

### ISSUE THREAD

**Issue by AyanavaKarmakar** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#112]
### Is your feature request related to a problem? Please describe.

ref: https://discord.com/channels/1166382233880383519/1287835652855038004/1287835655543722086

### Describe the solution you'd like to see

ref: https://discord.com/channels/1166382233880383519/1287835652855038004/1287835655543722086

### Describe alternate solutions

N/A

**Comment by aizaysi** [comment]
let me try this map clustering
