### ISSUE TITLE
feat: replace images in carousel present in landing page with "Trending Pandal" Cards

### ISSUE THREAD

**Issue by AyanavaKarmakar** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#114]
### Is your feature request related to a problem? Please describe.

Instead of images, we will instead show real time Trending Pandals on the landing page

### Describe the solution you'd like to see

1) remove images from carousel (`/index.astro` and `/bn/index.astro`) & idol images caching from `netlify.toml`
2) use trending pandal cards in the carousel instead. refer to the UI for Trending Pandal cards here - https://dev.pujo-atlas.ourkolkata.in/app
3) API - https://api-atlas.ourkolkata.in/swagger - `/pujo/list/trending`

### Describe alternate solutions

N/A

**Comment by Dyslex7c** [comment]
you can assign this issue to me
