### ISSUE TITLE
feat: clicking on "Near Me" or "Trending" Card should take user to `/app/pandals` and pan the map to zoom in on that location marker

### ISSUE THREAD

**Issue by AyanavaKarmakar** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#122]
### Is your feature request related to a problem? Please describe.

Currently, the cards only show the data but are not clickable. We want to take the users to their respective positions in the map so that they can navigate further

### Describe the solution you'd like to see

Behaviour should be same as clicking on searchbar results on "Pandals" tab

### Describe alternate solutions

N/A

**Comment by yashchaurasia667** [comment]
I think i can make this but where are the "Near me" and "Trending" buttons? Should I make those buttons?
(sorry if the question sounds dumb this is my first time working with an open source project)

**Comment by AyanavaKarmakar** [comment]
Hi @yashchaurasia667. You can find the "Near Me" and "Trending" cards here - https://dev.pujo-atlas.ourkolkata.in/app. The code for the cards can be found here - https://github.com/Pujo-Atlas-Kolkata/PujoAtlasKol-Web/tree/dev/src/components/app/home/Cards. We support the web app on mobile screen sizes only for now, so please open the URL in your phone or chrome mobile viewport.

Feel free to [join our discord server](https://discord.com/invite/xxSXWYf6d4) so that we can clear your doubts quickly!
