### ISSUE TITLE
feat: add `onClick` feedback to "settings" icon

### ISSUE THREAD

**Issue by AyanavaKarmakar** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#132]
### Is your feature request related to a problem? Please describe.

In https://dev.pujo-atlas.ourkolkata.in/app/* - when the settings icon is clicked, the settings panel shows up below. we also want to add feedback to the icon itself when clicked

### Describe the solution you'd like to see

1) rotate the icon a bit when tapped
2) go back to initial position when settings panel is closed

### Describe alternate solutions

open to suggestions in [discord](https://discord.com/invite/xxSXWYf6d4)

**Comment by debroopghosh11** [comment]
Hi, @AyanavaKarmakar , could you please assign this issue to me.
Thanks!

**Comment by AyanavaKarmakar** [comment]
Hi @debroopghosh11, I can see that you've joined our discord server. Please response there as it needs further discussion. After that this issue will be assigned to you.

**Comment by Dyslex7c** [comment]
you can assign this issue to me

**Comment by AyanavaKarmakar** [comment]
assigned as discussed on discord
