### ISSUE TITLE
feat: send ID of Pandal being clicked on in Pandal Map to BE

### ISSUE THREAD

**Issue by AyanavaKarmakar** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#141]
### Is your feature request related to a problem? Please describe.

When a user clicks on a pandal marker in the pandal map, we will pass that pandal id to BE. BE will use this to curate "Trending Pandals" list endpoint.

### Describe the solution you'd like to see

Whenever user clicks on a pandal marker, send the pandal's id to https://api-atlas.ourkolkata.in/pujo/searched. Refer: https://api-atlas.ourkolkata.in/swagger

### Describe alternate solutions

N/A

### Additional information

Refer: https://github.com/Pujo-Atlas-Kolkata/PujoAtlasKol-Web/blob/b87c391d7bb59a12b5ca1092f67199940a6fc091/src/components/app/home/Cards/PandalCard.tsx#L38-L42

**Comment by maranix** [comment]
Hey, I can work on this issue. If somebody else hasn't been working on it already can you assign it to me?

**Comment by AyanavaKarmakar** [comment]
Hi @maranix. Please join our [discord](https://discord.com/invite/xxSXWYf6d4). We will assign the issue after further discussion.

**Comment by AyanavaKarmakar** [comment]
Closed as trending algo has been updated
