### ISSUE TITLE
Setup View Transitions

### ISSUE THREAD

**Issue by TheHappyBaloney** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#15]
Please implement view transitions in the project following the guidelines in the [Astro View Transitions documentation](https://docs.astro.build/en/guides/view-transitions/). This will enhance the user experience by adding smooth transitions between pages.

**Comment by Heisen47** [comment]
hey , you just wanna have a view transition from "home" button to "EN/BN" button right with smooth animations?
