### ISSUE TITLE
Setup Sitemap

### ISSUE THREAD

**Issue by TheHappyBaloney** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#16]
Create and configure a sitemap for the site using the instructions in the [Astro Sitemap Integration Guide](https://docs.astro.build/en/guides/integrations-guide/sitemap/). This is essential for improving SEO and making the site more search engine-friendly.

**Comment by AyanavaKarmakar** [comment]
I will take care of this @TheHappyBaloney

**Comment by TheHappyBaloney** [comment]
> I will take care of this @TheHappyBaloney

Alrighty!

**Comment by AyanavaKarmakar** [comment]
putting this on hold till domain is finalized
