### ISSUE TITLE
bug: searchbar suggestions not showing up on Firefox Android

### ISSUE THREAD

**Issue by AyanavaKarmakar** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#163]
### Describe the bug

If the keyboard is open, searchbar results are not visible. They are only visbile when keyboard is closed

### To reproduce

Open http://atlas.ourkolkata.in/app/pandals and try searching something in the searchbar in Firefox Android

**Comment by AyanavaKarmakar** [comment]
assigning to @Dyslex7c as discussed on discord.

**Comment by Dyslex7c** [comment]
yes, you can assign this issue to me
