### ISSUE TITLE
bug: Make only the search bar sticky, allowing "Near Me" and "Trending" buttons to scroll

### ISSUE THREAD

**Issue by TheHappyBaloney** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#176]
### Describe the bug

**Currently, the entire top bar (including the search bar, "Near Me," and "Trending" buttons) stays sticky while users scroll, essentially hiding the main content aka the pandal cards.**

### To reproduce

Make only the search bar sticky, and allow the "Near Me" and "Trending" buttons to scroll off the screen as users move down the page. This will make the interface cleaner and provide more visible space for viewing pandals.

### Additional information

![Atlas Screen](https://github.com/user-attachments/assets/36af86ef-0cfc-4c9c-976b-84ca8207466d)

Please see screenshot for reference

**Comment by Dyslex7c** [comment]
you can assign this issue to me
