### ISSUE TITLE
Create In-House Icon Library System

### ISSUE THREAD

**Issue by TheHappyBaloney** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#18]
Develop an in-house icon library system where raw SVG code of icons is imported and exported as named icons through React components. This will streamline the use of icons across the project, ensuring consistency and easier maintenance.

Note: When creating the PR, use the build: prefix in the commit message.

**Comment by wriddhi** [comment]
Assign to me @TheHappyBaloney

**Comment by TheHappyBaloney** [comment]
> Assign to me @TheHappyBaloney

Alrighty!
