### ISSUE TITLE
bug: better UX for map

### ISSUE THREAD

**Issue by cu8code** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#182]
### Describe the bug

![Screenshot_2024-10-13-12-27-22-325_com brave browser](https://github.com/user-attachments/assets/bdaafcab-b544-40c7-b99b-a3791dbce985)

What dose the blue circle and Red Lines represent ?

### To reproduce

Just open the current deployment 

### Additional information

When I zoom into the blue circle they disappear!

**Comment by AyanavaKarmakar** [comment]
The circle represents the clustering of pandal markers. The color of the circle changes to blue or red depending on the number of pandals clustered.

By clicking on the cluster circle, the map will pan to the clustered area and display the individual markers that were previously clustered.

We are utilizing Google Map's clustering library for this purpose.

**Comment by cu8code** [comment]
Add some text informing the user, about what the circle represents! It's a good feature, but the UX is killing it!
