### ISSUE TITLE
feat: Add Cloudflare and and Sentry logo

### ISSUE THREAD

**Issue by TheHappyBaloney** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#184]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/83e8063f-a255-4a0b-b731-b2e1b8c5dea3)

### Describe the solution you'd like to see

Add cloudflare and sentry logo along with netlify.

### Describe alternate solutions

NA

**Comment by Dyslex7c** [comment]
you can assign this issue to me
