### ISSUE TITLE
feat: create UI for home page in webapp

### ISSUE THREAD

**Issue by AyanavaKarmakar** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#89]
### Is your feature request related to a problem? Please describe.

The home tab is current using some placeholder text. this should be replaced with the actual UI

### Describe the solution you'd like to see

create UI for the "home" tab based on this [Figma](https://www.figma.com/design/AUVPRXCSLODtimG3volaey/Pujo-Atlas-Web?node-id=283-3302&t=f2RWy40dzt5ZuouH-4) design

### Describe alternate solutions

N/A

### Additional information

`/pages/app/index.astro` is the relevant file

**Comment by Dyslex7c** [comment]
Hi there, I have contacted you over discord (Dr.Klaus) You can assign this issue to me
